#这是一个配置文件，所有主功能的开启和关闭都必须重启服务器/重新加载插件
plugin-message:
  #插件消息前缀
  message-prefix: '&e[UtilityToolbox] &6'

#自定义加入和离开服务器消息
join-and-leave-server-message:
  enable: true
  #是否开启第一次加入服务器的服务器消息内容
  first-join-server-message-enable: false
  message:
    player-join-server-message: '&a%player% join server'
    player-leave-server-message: '&c%player% leave server'
    player-first-join-server-message: '&a%player% first join server'

#加入服务器欢迎
join-server-welcome:
  enable: true
  #是否开启第一次加入服务器的加入欢迎
  first-join-server-welcome-enable: false
  message:
    join-server-welcome-message:
      - '&e[UtilityToolbox] &6欢迎使用本插件'
    first-join-server-welcome-message:
      - '&e[UtilityToolbox] &6欢迎使用本插件'

#自动发送服务器消息，类似公告
auto-send-server-messages:
  enable: false
  #间隔发送时间：默认秒
  time: 600
  message:
    send-messages:
      - '&e[UtilityToolbox] &6欢迎使用本插件'

#高频红石检测
anti-high-frequency-red-stone:
  enable: false
  #是否所有玩家都能看到红石被摧毁消息，否则只有拥有UtilityToolbox.AntiRedStoneMessage权限的用户才能看到
  is-broadcast-message: true
  #红石在检测时间内的限制次数
  limit: 50
  #检测时间，默认秒
  time: 5
  #检测的红石列表
  anti-red-stone-list:
    #默认红石、拉杆，可自行添加
    - 'minecraft:redstone_wire'
    - 'minecraft:lever'
  message:
    destroy-message: "玩家&3%player%&6附近存在高频红石，坐标&cx:%x% y:%y% z:%z%&6，已摧毁"

#限制高空流体
limit-high-altitude-fluid:
  enable: false
  #是否所有玩家都能看到流体被限制的消息，否则只有拥有UtilityToolbox.LimitFlowMessage权限的用户才能看到
  is-broadcast-message: true
  #限制高度
  limit-high: 120
  #限制的流体列表
  limit-fluid-list:
    #默认水和岩浆，该名字为流动液体的名字
    - 'minecraft:water'
    - 'minecraft:lava'
  #限制的世界，可使用 * 通配符为限制所有世界
  limit-world-list:
    - 'world'
  message:
    destroy-message: "玩家&3%player%&6附近存在高空流体，坐标&cx:%x% y:%y% z:%z%&6，已限制"

#服务器列表显示
server-list-display-modification:
  enable: false
  #最大玩家数
  max-player: 20
  #图标名称，放置在插件配置文件根目录下，规格必须为64*64，如果该图标不存在则无影响
  icon: icon.png
  message:
    first-line: '&e[UtilityToolbox] &6欢迎使用本插件'
    second-line: '&e[UtilityToolbox] &6欢迎使用本插件'

#连点左键限制
prevent-high-frequency-attacks:
  enable: false
  #是否所有玩家都能看到因高频左键被踢出服务器的消息，否则只有拥有UtilityToolbox.PlayerFrequencyAttacksKickMessage权限的用户才能看到
  is-broadcast-message: true
  #是否踢出服务器
  is-kill: false
  #在检测时间内的限制次数
  limit: 50
  #检测时间，默认秒
  time: 3
  message:
    player-kick-message: "&c你因疑似使用连点器被服务器踢出，若有疑问请联系服主，CPS:%cps%"
    broadcast-kick-message: "&c玩家&3%player%&c疑似使用连点器，已踢出服务器，CPS:%cps%"
    broadcast-no-kick-message: "&c玩家&3%player%&c疑似使用连点器，CPS:%cps%"

#主指令
utilitytoolbox:
  message:
    utilitytoolbox-command-error: '&c子指令无效或无子指令，正确格式: &6/UtilityToolbox <子指令>'
    utilitytoolbox-apply-reload: '&a配置文件重载成功'

#恢复生命值
heal:
  message:
    heal-self: '&a你已恢复状态'
    heal-others: '&a你已恢复&3%others-player%&a状态'
    heal-others-no-exist: '&c玩家&3%others-player%&c不存在，请检查玩家名字'
    heal-others-is-self: '你已恢复状态，你可以使用不带参数的指令来恢复自己'
    heal-others-no-permission: '&c你没有执行恢复他人状态指令的权限'
    heal-by-others: '你已被&3%player%&6恢复状态'
    heal-by-console: '你已被服务器恢复状态'
    heal-console-error: '&c控制台请执行恢复他人状态的指令: &6heal <玩家名称>'
    heal-command-error: '&c恢复状态指令格式错误，正确格式: &6/heal [玩家名称]'

#飞行
fly:
  message:
    fly-self-open: '&a你已开启飞行'
    fly-self-close: '&a你已关闭飞行'
    fly-others-open: '&a你已开启&3%others-player%&a的飞行'
    fly-others-close: '&a你已关闭&3%others-player%&a的飞行'
    fly-others-no-exist: '&c玩家&3%others-player%&c不存在，请检查玩家名字'
    fly-others-is-self-open: '你已开启飞行，可以使用不带参数的指令来开关飞行'
    fly-others-is-self-close: '你已关闭飞行，可以使用不带参数的指令来开关飞行'
    fly-others-no-permission: '&c你没有执行开关他人飞行指令的权限'
    fly-by-others-open: '你已被&3%player%&6开启飞行'
    fly-by-others-close: '你已被&3%player%&6关闭飞行'
    fly-by-console-open: '你已被服务器开启飞行'
    fly-by-console-close: '你已被服务器关闭飞行'
    fly-console-error: '&c控制台请执行开关他人飞行的指令: &6fly <玩家名称>'
    fly-command-error: '&c开关飞行指令格式错误，正确格式: &6/fly [玩家名称]'

#飞行速度
flyspeed:
  message:
    fly-speed-self-reset: '&a你已重置飞行速度'
    fly-speed-self: '&a你已修改飞行速度为%fly-speed%'
    fly-speed-self-args-error: '&c飞行速度参数错误，飞行速度只能为0-10，默认速度为1'
    fly-speed-others: '&a你已修改&3%others-player%&a的飞行速度为%fly-speed%'
    fly-speed-others-reset: '&a你已重置&3%others-player%&a的飞行速度'
    fly-speed-others-reset-is-self: '你已重置飞行速度，修改自己可以不输入玩家名称'
    fly-speed-others-is-self: '你已修改飞行速度为%fly-speed%，修改自己可以不输入玩家名称'
    fly-speed-others-no-exist: '&c玩家&3%others-player%&c不存在，请检查玩家名字'
    fly-speed-others-no-permission: '&c你没有修改他人飞行速度指令的权限'
    fly-speed-by-others: '你已被&3%player%&6修改飞行速度为%fly-speed%'
    fly-speed-by-others-reset: '你已被&3%player%&6重置飞行速度'
    fly-speed-by-console: '你已被服务器修改飞行速度为%fly-speed%'
    fly-speed-by-console-reset: '你已被服务器重置飞行速度'
    fly-speed-console-error: '&c控制台请执行修改他人飞行速度的指令: &6flyspeed [速度] <玩家名称>'
    fly-speed-command-error: '&c修改飞行速度指令格式错误，格式: &6/flyspeed [速度] [玩家名称]'

#行走速度
walkspeed:
  message:
    walk-speed-self-reset: '&a你已重置移动速度'
    walk-speed-self: '&a你已修改移动速度为%walk-speed%'
    walk-speed-self-args-error: '&c移动速度参数错误，移动速度只能为0到10，默认速度为2'
    walk-speed-others: '&a你已修改&3%others-player%&a的移动速度为%walk-speed%'
    walk-speed-others-reset: '&a你已重置&3%others-player%&a的移动速度'
    walk-speed-others-reset-is-self: '你已重置移动速度，修改自己可以不输入玩家名称'
    walk-speed-others-is-self: '你已修改移动速度为%walk-speed%，修改自己可以不输入玩家名称'
    walk-speed-others-no-exist: '&c玩家&3%others-player%&c不存在，请检查玩家名字'
    walk-speed-others-no-permission: '&c你没有修改他人移动速度指令的权限'
    walk-speed-by-others: '你已被&3%player%&6修改移动速度为%walk-speed%'
    walk-speed-by-others-reset: '你已被&3%player%&6重置移动速度'
    walk-speed-by-console: '你已被服务器修改移动速度为%walk-speed%'
    walk-speed-by-console-reset: '你已被服务器重置移动速度'
    walk-speed-console-error: '&c控制台请执行修改他人移动速度的指令: &6walkspeed [速度] <玩家名称>'
    walk-speed-command-error: '&c修改移动速度指令格式错误，格式: &6/walkspeed [速度] [玩家名称]'

#申请传送
tpa:
  message:
    tpa-others-no-exist: '&c玩家&3%others-player%&c不存在，请检查玩家名字'
    tpa-others-identical: '&c请不要发送重复传送请求'
    tpa-auto-tpacancel: '已自动取消上一个传送请求'
    tpa-auto-tpacancel-others: '玩家&3%player%&6已取消传送请求'
    tpa-apply: '&a传送请求已发送给玩家&3%others-player%'
    tpa-apply-others: '玩家&3%player%&6请求传送到你这里'
    tpa-apply-tpacancel-tips: '取消请求输入: &c/tpacancel'
    tpa-apply-accept-tips: '同意请求输入: &a/tpaccept'
    tpa-apply-deny-tips: '拒绝请求输入: &c/tpadeny'
    tpa-console-error: '&c控制台无法使用申请传送相关指令'
    tpa-command-error: '&c传送指令格式错误，正确格式: &6/tpa <其他玩家名称>'
    tpa-others-leave-server: '玩家&3%others-player%&6已离开服务器，已自动取消其传送请求'

#取消传送
tpacancel:
  message:
    tpacancel-apply: '&a已取消传送请求'
    tpacancel-others: '玩家&3%player%&6已取消传送请求'
    tpacancel-no-tpa-error: '&c你没有待处理的传送请求'
    tpacancel-console-error: '&c控制台无法使用申请传送相关指令'

#同意传送
tpaccept:
  message:
    tpaccept-apply: '&a你已接受玩家&3%others-player%&a的传送请求'
    tpaccept-apply-is-self: '&c请不要接受自己的传送请求'
    tpaccept-apply-others: '你向玩家&3%player%&6申请的传送请求已被接受'
    tpaccept-console-error: '&c控制台无法使用申请传送相关指令'
    tpaccept-others-no-exist: '&c玩家&3%others-player%&c不存在，请检查玩家名字'
    tpaccept-command-error: '&c同意请求指令格式错误，正确格式: &6/tpaccept [其他玩家名称]'
    tpaccept-no-tpa-error: '&c你没有待处理的传送请求'
    tpaccept-no-others-player-tpa-error: '&c你没有玩家&3%others-player%&c的传送请求'

#拒绝传送
tpadeny:
  message:
    tpadeny-apply: '&a你已拒绝玩家&3%others-player%&a的传送请求'
    tpadeny-apply-is-self: '&c请不要拒绝自己的传送请求'
    tpadeny-apply-others: '你向玩家&3%player%&6申请的传送请求已被拒绝'
    tpadeny-console-error: '&c控制台无法使用申请传送相关指令'
    tpadeny-others-no-exist: '&c玩家&3%others-player%&c不存在，请检查玩家名字'
    tpadeny-command-error: '&c拒绝请求指令格式错误，正确格式: &6/tpadeny [其他玩家名称]'
    tpadeny-no-tpa-error: '&c你没有待处理的传送请求'
    tpadeny-no-others-player-tpa-error: '&c你没有玩家&3%others-player%&c的传送请求'

#随机传送
tpr:
  #是否以世界出生点为中心，否则就以玩家为中心
  respawn-center: true
  #同意随机传送列表
  allow-world:
    - '*'
  #危险的方块，不会传送到该方块上
  dangerous-block:
    - 'minecraft:water'
    - 'minecraft:lava'
    - 'minecraft:cactus'
    - 'minecraft:magma_block'
    - 'minecraft:spawner'
    - 'minecraft:fire'
    - 'minecraft:soul_fire'
  #最大随机的x范围
  random-x: 10000
  #最大随机的z范围
  random-z: 10000
  message:
    tpr-searching: "&6正在定位安全的传送位置，请不要连续使用随机传送"
    tpr-apply: "&a你已随机传送，当前坐标&6 x:%x% y:%y% z:%z%"
    tpr-world-error: "&c世界&3%world%&c禁止随机传送"
    tpr-console-error: "&c控制台无法使用随机传送相关指令"

#设置家
sethome:
  #允许设置家的世界，默认 * 为所有世界都允许设置家
  allow-world:
    - '*'
  message:
    sethome-apply: '&a已将此位置设为&3%name%&a家'
    sethome-world-error: '&c世界&3%world%&c禁止设置家'
    sethome-console-error: '&c控制台无法使用家相关指令'
    sethome-command-error: '&c设置家指令格式错误，正确格式: &6/sethome [name]'

#回家
home:
  message:
    home-apply: '&a你已传送回&3%name%&a家'
    home-no-exist: '&c暂无&3%name%&c家，请使用&6/sethome [name]&c指令设置家的位置'
    home-console-error: '&c控制台无法使用家相关指令'
    home-command-error: '&c回家指令格式错误，正确格式: &6/sethome [name]'

#展示文本代码
showtextcode:
  message:
    showtextcode-command-error: '&c展示文本代码指令格式错误，正确格式: &6/showtextcolor'
    show-list:
      - '&c文本代码列表------------------------------'
      - '&11 深紫 &7/ &99（淡紫）'
      - '&22 墨绿 &7/ &aa（碧绿）'
      - '&33 深蓝 &7/ &bb（天蓝）'
      - '&44 深红 &7/ &cc（大红）'
      - '&55 粉红 &7/ &dd（亮粉红）'
      - '&66 橙色 &7/ &ee（金色）'
      - '&77 浅灰 &7/ &ff（白色）'
      - '&88 深灰 &7/ &00（黑色）'
      - 'k是乱码(有非英文字符就会无效，不展示)'
      - '&ll是粗体字'
      - '&oo是斜体字'
      - '&rr是恢复到原始效果'
      - '&mm是删除线'
      - '&nn是下划线'
      - '&c展示列表结束------------------------------'

#等同于自己使用/kill指令
killself:
  message:
    killself-apply: '&a已让服务器执行自杀指令'
    killself-console-error: '&c控制台请使用官方指令：kill [目标]'
    killself-command-error: '&c自杀指令格式错误，正确格式: &6/killself'

#传送到上一个传送/死亡的位置
back:
  message:
    back-apply: '&a你已回到被传送前的位置'
    back-died-tips: '你在下一次传送前可使用&c/back&6指令回到死亡位置'
    back-died-no-tp-tips: '服务器&c/back&6指令已记录你的死亡位置'
    back-no-location: '&c你暂时没有返回的位置'
    back-console-error: '&c控制台无法使用返回指令'
    back-command-error: '&c返回指令格式错误，正确格式: &6/back'

#切换服务器是否允许指令传送
teleport:
  message:
    teleport-allow: '&a服务器已恢复使用指令传送'
    teleport-allow-reason: '&a服务器已恢复使用指令传送，原因: &6%reason%'
    teleport-deny: '&c服务器已禁止指令传送'
    teleport-deny-apply: '&c服务器已禁止指令传送，传送失败'
    teleport-deny-reason: '&c服务器已禁止指令传送，原因: &6%reason%'
    teleport-command-error: '&c服务器是否允许指令传送格式错误，正确格式: &6/teleport [reason]'

#复制物品
copyres:
  #排除列表(用于排除通配符内的物品)写法，例如钻石甲：minecraft:diamond_chestplate
  exclude-list:
    - ''
  #黑名单，写法：钻石甲：minecraft:diamond_chestplate
  black-list:
  #默认禁用:附魔金苹果、金苹果、金萝卜、黄金、金粒、金块、tnt、火药、粗金块、粗金
    - 'minecraft:enchanted_golden_apple'
    - 'minecraft:golden_apple'
    - 'minecraft:golden_carrot'
    - 'minecraft:gold_ingot'
    - 'minecraft:gold_nugget'
    - 'minecraft:gold_block'
    - 'minecraft:tnt'
    - 'minecraft:gunpowder'
    - 'minecraft:raw_gold_block'
    - 'minecraft:raw_gold'
  #通配符列表写法(只写前缀)，例如minecraft:开头的所有物品，minecraft:
  wildcard-list:
    - ''
  message:
    copyres-apply: '&a你已复制&3%res%&a物品'
    copyres-deny: '&c物品&3%res%&c禁止复制'
    copyres-console-error: '&c控制台请使用官方指令：&6give <玩家> <物品[参数]> [数量]'
    copyres-command-error: '&c复制物品指令格式错误，正确格式: &6/copyres'

#模式切换
playmode:
  message:
    playmode-apply: '&a已让服务器执行切换模式指令'
    playmode-console-error: '&c控制台请使用官方指令：&6gamemode <模式> <玩家>'
    playmode-command-error: '&c切换模式指令格式错误，正确格式: &6/playmode <游戏模式>'
    playmode-no-permission-error: '&c你没有切换到模式&3%gamemode%&c的权限'

#设置传送点
settpp:
  #允许设置的世界，默认 * 通配符为全世界都允许设置
  allow-world:
    - '*'
  message:
    settpp-apply: '&a已将此位置设为&3%tp-name%&a传送点'
    settpp-world-error: '&c世界&3%world%&c禁止设置传送点'
    settpp-console-error: '&c控制台无法使用传送点相关指令'
    settpp-command-error: '&c设置传送点指令格式错误，正确格式: &6/settpp [tpname]'

#传送到传送点
tpp:
  message:
    tpp-apply: '&a你已传送到&3%tp-name%&a传送点'
    tpp-no-exist: '&c传送点&3%tp-name%&c不存在，请检查传送点名称是否正确'
    tpp-console-error: '&c控制台无法使用传送点相关指令'
    tpp-command-error: '&c回到传送点指令错误，正确格式: &6/tpp [tpname]'

#召集玩家
musterplayer:
  #召集完成后，传送的等待时间，默认秒
  time: 3
  message:
    musterplayer-apply-start: '&a已广播召集所有玩家到此位置，请等待所有玩家处理请求'
    musterplayer-apply-start-repeat: '&c玩家&3%player%&c已发起召集请求，请等待该召集结束后再发起召集'
    musterplayer-apply-start-error: '&c无其他在线玩家，请不要发起召集玩家请求'
    musterplayer-apply-start-others: '玩家&3%player%&6正在召集所有玩家，请及时处理请求'
    musterplayer-apply-start-others-reason: '玩家&3%player%&6正在召集所有玩家，原因: &c%reason%&c，请及时处理请求'
    musterplayer-apply-again: '&a已发起上一次召集请求，请等待所有玩家处理请求'
    musterplayer-apply-again-error: '&c没有上一次召集请求，请使用&6/musterplayer start&c指令发起新的召集'
    musterplayer-apply-cancel-consloe: '控制台已取消此次召集请求'
    musterplayer-apply-cancel-player: '&a你已取消此次召集请求'
    musterplayer-apply-cancel-player-others: '玩家&c%player%&6已取消此次召集请求'
    musterplayer-apply-end: '玩家&3%player%&6已提前结束召集，同意召集的玩家已传送至召集位置'
    musterplayer-apply-end-time: '玩家&3%player%&6提前结束召集，同意召集的玩家将在&c%time%&6秒后立即传送'
    musterplayer-apply-end-tp: '你已传送至召集位置'
    musterplayer-end: '已完成召集，同意召集的玩家已传送至召集位置'
    musterplayer-end-time: '已完成召集，同意召集玩家将在&c%time%秒&6后立即传送'
    musterplayer-apply-ccept: '玩家&3%player%&6已接受召集'
    musterplayer-apply-deny: '玩家&c%player%&6已拒绝召集'
    musterplayer-apply-list-allow: '已同意召集的玩家: &a%player-list%'
    musterplayer-apply-list-deny: '已拒绝召集的玩家: &c%player-list%'
    musterplayer-apply-list-deal-with: '还未处理召集的玩家: &7%player-list%'
    musterplayer-cancel-tips: '取消召集输入: &c/musterplayer cancel'
    musterplayer-end-tips: '结束召集输入: &c/musterplayer end'
    musterplayer-accept-tips: '同意召集输入: &a/musterplayer ccept'
    musterplayer-deny-tips: '拒绝召集输入: &c/musterplayer deny'
    musterplayer-others-tips: '所有玩家处理召集请求后或发起者提前结束召集，才会进行传送'
    musterplayer-apply-error: '&c没有需要处理的召集请求'
    musterplayer-player-leave-convenor: '召集者&3%player%&6已离开服务器，已取消此次召集'
    musterplayer-player-leave-callee: '被召集者&3%player%&6已离开服务器，已在被召集列表中移除该玩家'
    musterplayer-console-error: '&c控制台仅能使用&6musterplayer cancel&c指令取消玩家召集'
    musterplayer-command-error: '&c召集指令错误，正确格式: &6/musterplayer <参数>'

#重生后自动回到死亡位置
rebirthinplace:
  message:
    rebirthinplace-apply-open: '&a你已开启原地重生'
    rebirthinplace-apply-close: '&a你已关闭原地重生'
    rebirthinplace-apply: '你已原地重生'
    rebirthinplace-console-error: '&c控制台无法使用此命令'

#自动重生
autorespawn:
  message:
    autorespawn-apply-open: '&a你已开启自动重生'
    autorespawn-apply-close: '&a你已关闭自动重生'
    autorespawn-apply: '已自动跳过死亡结算界面'
    autorespawn-console-error: '&c控制台无法使用此命令'

#发送控制台指令
sendconsole:
  message:
    sendconsole-apply-success: '&a服务器执行&6%command%&a指令成功'
    sendconsole-apply-fail: '&c服务器执行&6%command%&c指令失败，请检查指令是否正确'
    sendconsole-command-error: '&c发送控制台指令格式错误，正确格式: &6/sendconsole <arg...>'