#这是一个配置文件，所有主功能的开启和关闭都必须重启服务器/重新加载插件
plugin-message:
  message-prefix: '&e[UtilityToolbox] &7'
  reload-message: '配置文件重载成功'
  command-args-error: '子指令无效或无子指令，正确格式: &c/UtilityToolbox <子指令>'

#自定义加入和离开服务器消息
join-and-leave-server-message:
  enable: true
  first-join-server-message-enable: false
  message:
    player-join-server-message: '&a%player% join server'
    player-leave-server-message: '&c%player% leave server'
    player-first-join-server-message: '&a%player% first join server'

#加入服务器欢迎
join-server-welcome:
  enable: true
  first-join-server-welcome-enable: false
  message:
    join-server-welcome-message:
      - '&e[UtilityToolbox] &7欢迎使用本插件'
    first-join-server-welcome-message:
      - '&e[UtilityToolbox] &7欢迎第一次使用本插件'

#自动发送服务器消息，类似公告
auto-send-server-messages:
  enable: false
  #默认秒
  time: 600
  message:
    send-messages:
      - '&e[UtilityToolbox] &7欢迎使用本插件'

#高频红石检测
anti-high-frequency-red-stone:
  enable: false
  #是否所有玩家都能看到红石被摧毁消息，否则只有UtilityToolbox.AntiRedStoneMessage权限的用户才能看
  is-broadcast-message: true
  #红石在检测时间内的限制次数
  limit: 50
  #检测时间，默认秒
  time: 5
  #检测的红石列表
  anti-red-stone-list:
    #默认红石、拉杆，可自行添加
    - 'minecraft:redstone_wire'
    - 'minecraft:lever'
  message:
    destroy-message: "玩家&3%player%&7附近存在高频红石，坐标&3x:%x% y:%y% z:%z%&7，已摧毁"

#限制高空流体
limit-high-altitude-fluid:
  enable: false
  #是否所有玩家都能看到流体被限制的消息，否则只有UtilityToolbox.LimitFlowMessage权限的用户才能看
  is-broadcast-message: true
  #限制高度
  limit-high: 80
  limit-fluid-list:
    #默认水和岩浆，该名字为流动液体的名字
    - 'minecraft:water'
    - 'minecraft:lava'
  #限制的世界
  limit-world-list:
    #*为限制所有世界
    - '*'
  message:
    destroy-message: "玩家&3%player%&7附近存在高空流体，坐标&3x:%x% y:%y% z:%z%&7，已限制"

#玩家自动重生
auto-respawn:
  enable: false

#玩家无死亡掉落
no-death-drop:
  enable: false

#服务器列表显示
server-list-display-modification:
  enable: false
  #最大玩家数
  max-player: 20
  #图标名称，放置在插件配置文件根目录下，规格必须为64*64，如果该图标不存在则无影响
  icon: icon.png
  message:
    first-line: '&e[UtilityToolbox] &7欢迎使用本插件'
    second-line: '&e[UtilityToolbox] &7欢迎使用本插件'

#恢复生命值
heal:
  message:
    heal-self: '你已恢复生命值'
    heal-others: '你已恢复&3%others-player%&7的生命值'
    heal-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    heal-others-is-self: '你已恢复生命值，可以使用不带参数的指令来恢复自己'
    heal-others-no-permission: '你没有执行恢复他人生命值指令的权限'
    heal-by-others: '你已被&3%player%&7恢复生命值'
    heal-by-console: '你已被服务器恢复生命值'
    heal-console-error: '控制台请执行恢复他人生命值的指令: &cheal <玩家名称>'
    heal-command-error: '恢复生命值指令格式错误，正确格式: &c/heal [玩家名称]'

#恢复饱食度
feed:
  message:
    feed-self: '你已恢复饱食度'
    feed-others: '你已恢复&3%others-player%&7的饱食度'
    feed-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    feed-others-is-self: '你已恢复饱食度，可以使用不带参数的指令来恢复自己'
    feed-others-no-permission: '你没有执行恢复他人饱食度指令的权限'
    feed-by-others: '你已被&3%player%&7恢复饱食度'
    feed-by-console: '你已被服务器恢复饱食度'
    feed-console-error: '控制台请执行恢复他人饱食度的指令: &cfeed <玩家名称>'
    feed-command-error: '恢复饱食度指令格式错误，正确格式: &c/feed [玩家名称]'

#恢复生命值和饱食度
#当拥有恢复生命值和饱食度指令时该指令可使用
healandfeed:
  message:
    heal-and-feed-self: '你已恢复生命值和饱食度'
    heal-and-feed-others: '你已恢复&3%others-player%&7的生命值和饱食度'
    heal-and-feed-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    heal-and-feed-others-is-self: '你已恢复生命值和饱食度，可以使用不带参数的指令来恢复自己'
    heal-and-feed-others-no-permission: '你没有执行恢复他人生命值和饱食度指令的权限'
    heal-and-feed-by-others: '你已被&3%player%&7恢复生命值和饱食度'
    heal-and-feed-by-console: '你已被服务器恢复生命值和饱食度'
    heal-and-feed-console-error: '控制台请执行恢复他人生命值和饱食度的指令: &chealandfeed <玩家名称>'
    heal-and-feed-command-error: '恢复生命值和饱食度指令格式错误，正确格式: &c/healandfeed [玩家名称]'

#飞行
fly:
  message:
    fly-self-open: '你已开启飞行'
    fly-self-close: '你已关闭飞行'
    fly-others-open: '你已开启&3%others-player%&7的飞行'
    fly-others-close: '你已关闭&3%others-player%&7的飞行'
    fly-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    fly-others-is-self-open: '你已开启飞行，可以使用不带参数的指令来开关飞行'
    fly-others-is-self-close: '你已关闭飞行，可以使用不带参数的指令来开关飞行'
    fly-others-no-permission: '你没有执行开关他人飞行指令的权限'
    fly-by-others-open: '你已被&3%player%&7开启飞行'
    fly-by-others-close: '你已被&3%player%&7关闭飞行'
    fly-by-console-open: '你已被服务器开启飞行'
    fly-by-console-close: '你已被服务器关闭飞行'
    fly-console-error: '控制台请执行开关他人飞行的指令: &cfly <玩家名称>'
    fly-command-error: '开关飞行指令格式错误，正确格式: &c/fly [玩家名称]'

#飞行速度
flyspeed:
  message:
    fly-speed-self-reset: '你已重置飞行速度'
    fly-speed-self: '你已修改飞行速度为%fly-speed%'
    fly-speed-self-args-error: '飞行速度参数错误，飞行速度只能为0-10，默认速度为1'
    fly-speed-others: '你已修改&3%others-player%&7的飞行速度为%fly-speed%'
    fly-speed-others-reset: '你已重置&3%others-player%&7的飞行速度'
    fly-speed-others-reset-is-self: '你已重置飞行速度，修改自己可以不输入玩家名称'
    fly-speed-others-is-self: '你已修改飞行速度为%fly-speed%，修改自己可以不输入玩家名称'
    fly-speed-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    fly-speed-others-no-permission: '你没有修改他人飞行速度指令的权限'
    fly-speed-by-others-reset: '你已被&3%player%&7重置飞行速度'
    fly-speed-by-console-reset: '你已被服务器重置飞行速度'
    fly-speed-by-others: '你已被&3%player%&7修改飞行速度为%fly-speed%'
    fly-speed-by-console: '你已被服务器修改飞行速度为%fly-speed%'
    fly-speed-console-error: '控制台请执行修改他人飞行速度的指令: &cflyspeed [速度] <玩家名称>'
    fly-speed-command-error: '修改飞行速度指令格式错误，格式: &c/flyspeed [速度] [玩家名称]'

#行走速度
walkspeed:
  message:
    walk-speed-self-reset: '你已重置移动速度'
    walk-speed-self: '你已修改移动速度为%walk-speed%'
    walk-speed-self-args-error: '移动速度参数错误，移动速度只能为0到10，默认速度为2'
    walk-speed-others: '你已修改&3%others-player%&7的移动速度为%walk-speed%'
    walk-speed-others-reset: '你已重置&3%others-player%&7的移动速度'
    walk-speed-others-reset-is-self: '你已重置移动速度，修改自己可以不输入玩家名称'
    walk-speed-others-is-self: '你已修改移动速度为%walk-speed%，修改自己可以不输入玩家名称'
    walk-speed-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    walk-speed-others-no-permission: '你没有修改他人移动速度指令的权限'
    walk-speed-by-others: '你已被&3%player%&7修改移动速度为%walk-speed%'
    walk-speed-by-others-reset: '你已被&3%player%&7重置移动速度'
    walk-speed-by-console: '你已被服务器修改移动速度为%walk-speed%'
    walk-speed-by-console-reset: '你已被服务器重置移动速度'
    walk-speed-console-error: '控制台请执行修改他人移动速度的指令: &cwalkspeed [速度] <玩家名称>'
    walk-speed-command-error: '修改移动速度指令格式错误，格式: &c/walkspeed [速度] [玩家名称]'

#申请传送
tpa:
  message:
    tpa-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    tpa-others-identical: '请不要发送重复申请'
    tpa-auto-tpacancel: '已自动取消上一个传送请求'
    tpa-auto-tpacancel-others: '玩家&3%player%&7已取消传送请求'
    tpa-apply: '传送请求已发送给玩家&3%others-player%'
    tpa-apply-others: '玩家&3%player%&7请求传送到你这里'
    tpa-apply-tpacancel-tips: '取消请求输入: &c/tpacancel'
    tpa-apply-accept-tips: '同意请求输入: &c/tpaccept'
    tpa-apply-deny-tips: '拒绝请求输入: &c/tpadeny'
    tpa-console-error: '控制台无法使用传送相关指令'
    tpa-command-error: '传送指令格式错误，正确格式: &c/tpa <其他玩家名称>'
    tpa-others-leave-server: '玩家&3%others-player%&7已离开服务器，已自动取消其传送请求'

#取消传送
tpacancel:
  message:
    tpacancel-apply: '已取消传送请求'
    tpacancel-others: '玩家&3%player%&7已取消传送请求'
    tpacancel-no-tpa-error: '你没有待处理的传送请求'
    tpacancel-console-error: '控制台无法使用传送相关指令'

#同意传送
tpaccept:
  message:
    tpaccept-apply: '你已接受玩家&3%others-player%&7的传送请求'
    tpaccept-apply-is-self: '请不要接受自己的传送请求'
    tpaccept-apply-others: '你向玩家&3%player%&7申请的传送请求已被接受'
    tpaccept-console-error: '控制台无法使用传送相关指令'
    tpaccept-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    tpaccept-command-error: '同意请求指令格式错误，正确格式: &c/tpaccept [其他玩家名称]'
    tpaccept-no-tpa-error: '你没有待处理的传送请求'
    tpaccept-no-others-player-tpa-error: '你没有玩家&3%others-player%&7的传送请求'

#拒绝传送
tpadeny:
  message:
    tpadeny-apply: '你已拒绝玩家&3%others-player%&7的传送请求'
    tpadeny-apply-is-self: '请不要拒绝自己的传送请求'
    tpadeny-apply-others: '你向玩家&3%player%&7申请的传送请求已被拒绝'
    tpadeny-console-error: '控制台无法使用传送相关指令'
    tpadeny-others-no-exist: '玩家&3%others-player%&7不存在，请检查玩家名字'
    tpadeny-command-error: '拒绝请求指令格式错误，正确格式: &c/tpadeny [其他玩家名称]'
    tpadeny-no-tpa-error: '你没有待处理的传送请求'
    tpadeny-no-others-player-tpa-error: '你没有玩家&3%others-player%&7的传送请求'

#设置家
sethome:
  allow-world:
    - 'world'
  message:
    sethome-apply: '已将此位置设为家'
    sethome-world-error: '世界&3%world%&7禁止设置家'
    sethome-console-error: '控制台无法使用家相关指令'
    sethome-command-error: '设置家指令格式错误，正确格式: &c/sethome'

#回家
home:
  message:
    home-apply: '你已传送回家'
    home-no-exist: '暂无家，请使用&c/sethome&7指令设置家的位置'
    home-console-error: '控制台无法使用家相关指令'
    home-command-error: '设置家指令格式错误，正确格式: &c/sethome'

#展示文本代码
showtextcode:
  message:
    showtextcode-command-error: '展示文本代码指令格式错误，正确格式: &c/showtextcolor'
    show-list:
      - '&c文本代码列表------------------------------'
      - '&11 深紫 &7/ &99（淡紫）'
      - '&22 墨绿 &7/ &aa（碧绿）'
      - '&33 深蓝 &7/ &bb（天蓝）'
      - '&44 深红 &7/ &cc（大红）'
      - '&55 粉红 &7/ &dd（亮粉红）'
      - '&66 橙色 &7/ &ee（金色）'
      - '&77 浅灰 &7/ &ff（白色）'
      - '&88 深灰 &7/ &00（黑色）'
      - 'k是乱码(有非英文字符就会无效，不展示)'
      - '&ll是粗体字'
      - '&oo是斜体字'
      - '&rr是恢复到原始效果'
      - '&mm是删除线'
      - '&nn是下划线'
      - '&c展示列表结束------------------------------'

#等同于自己使用/kill指令
killself:
  message:
    killself-apply: '已让服务器执行自杀指令'
    killself-console-error: '控制台请使用官方指令：kill [目标]'
    killself-command-error: '自杀指令格式错误，正确格式: &c/killself'

#传送到上一个传送/死亡的位置
back:
  message:
    back-apply: '你已回到被传送前的位置'
    back-died-tips: '服务器已允许使用&c/back&7指令回到死亡位置'
    back-died-no-tp-tips: '服务器&c/back&7指令已记录你的死亡位置'
    back-no-location: '你暂时没有返回的位置'
    back-console-error: '控制台无法使用返回指令'
    back-command-error: '返回指令格式错误，正确格式: &c/back'

#切换服务器是否允许指令传送
teleport:
  message:
    teleport-allow: '&a服务器已恢复使用指令传送'
    teleport-allow-reason: '&a服务器已恢复使用指令传送，原因: &6%reason%'
    teleport-deny: '&c服务器已临时禁止指令传送'
    teleport-deny-apply: '&c服务器已临时禁止指令传送，传送失败'
    teleport-deny-reason: '&c服务器已临时禁止指令传送，原因: &6%reason%'
    teleport-command-error: '服务器是否允许指令传送格式错误，正确格式: &c/teleport [原因]'

#复制物品
copyres:
  #排除列表(用于排除通配符内的物品)写法，例如钻石甲：minecraft:diamond_chestplate
  exclude-list:
    - ''
  #黑名单，写法：钻石甲：minecraft:diamond_chestplate
  black-list:
  #默认禁用:附魔金苹果、金苹果、金萝卜、黄金、金粒、金块、tnt、火药
    - 'minecraft:enchanted_golden_apple'
    - 'minecraft:golden_apple'
    - 'minecraft:golden_carrot'
    - 'minecraft:gold_ingot'
    - 'minecraft:gold_nugget'
    - 'minecraft:gold_block'
    - 'minecraft:tnt'
    - 'minecraft:gunpowder'
  #通配符列表写法(只写前缀)，例如minecraft:开头的所有物品，minecraft:
  wildcard-list:
    - ''
  message:
    copyres-apply: '你已复制&3%res%&7物品'
    copyres-deny: '物品&3%res%&7禁止复制'
    copyres-console-error: '控制台请使用官方指令：give <玩家> <物品[参数]> [数量]'
    copyres-command-error: '复制物品指令格式错误，正确格式: &c/copyres'

#模式切换
playmode:
  message:
    playmode-apply: '已让服务器执行切换模式指令'
    playmode-console-error: '控制台请使用官方指令：gamemode <模式> <玩家>'
    playmode-command-error: '切换模式指令格式错误，正确格式: &c/playmode <游戏模式>'
    playmode-no-permission-error: '你没有切换到模式&3%gamemode%&7的权限'

#设置临时传送点
setsnaptp:
  #允许设置的世界
  allow-world:
    - '*'
  message:
    setsnaptp-apply: '已将此位置设为临时传送点，下线后删除'
    setsnaptp-world-error: '世界&3%world%&7禁止设置临时传送点'
    setsnaptp-console-error: '控制台无法使用临时传送点相关指令'
    setsnaptp-command-error: '设置临时传送点指令格式错误，正确格式: &c/setsnaptp'

#传送到临时传送点
snaptp:
  message:
    snaptp-apply: '你已传送回临时传送点'
    snaptp-no-exist: '暂无临时传送点，请使用&c/setsnaptp&7指令设置'
    snaptp-console-error: '控制台无法使用临时传送点相关指令'
    snaptp-command-error: '传送回临时传送点指令错误，正确格式: &c/snaptp'

#召集玩家
musterplayer:
  #召集完成后，传送的等待时间，默认秒
  time: 3
  message:
    musterplayer-apply-start: '已广播召集所有玩家到此位置，请等待所有玩家处理请求'
    musterplayer-apply-start-repeat: '玩家&3%player%&7已发起召集请求，请等待该召集结束后再发起召集'
    musterplayer-apply-start-error: '无其他在线玩家，请不要发起召集玩家请求'
    musterplayer-apply-start-others: '玩家&3%player%&7正在召集所有玩家，请及时处理请求'
    musterplayer-apply-start-others-reason: '玩家&3%player%&7正在召集所有玩家，原因: &6%reason%&7，请及时处理请求'
    musterplayer-apply-again: '已发起上一次召集请求，请等待所有玩家处理请求'
    musterplayer-apply-again-error: '没有上一次召集请求，请使用&c/musterplayer start&7指令发起新的召集'
    musterplayer-apply-cancel-consloe: '控制台已取消此次召集请求'
    musterplayer-apply-cancel-player: '你已取消此次召集请求'
    musterplayer-apply-cancel-player-others: '玩家&c%player%&7已取消此次召集请求'
    musterplayer-apply-end: '玩家%player%已提前结束召集，同意召集的玩家已传送至召集位置'
    musterplayer-apply-end-time: '玩家&3%player%&7提前结束召集，同意召集的玩家将在&c%time%&7秒后立即传送'
    musterplayer-apply-end-tp: '你已传送至召集位置'
    musterplayer-end: '已完成召集，同意召集的玩家已传送至召集位置'
    musterplayer-end-time: '已完成召集，同意召集玩家将在&c%time%秒&7后立即传送'
    musterplayer-apply-ccept: '玩家&3%player%&7已接受召集'
    musterplayer-apply-deny: '玩家&c%player%&7已拒绝召集'
    musterplayer-apply-list-allow: '已同意召集的玩家: &a%player-list%'
    musterplayer-apply-list-deny: '已拒绝召集的玩家: &c%player-list%'
    musterplayer-apply-list-deal-with: '还未处理召集的玩家: &6%player-list%'
    musterplayer-cancel-tips: '取消召集输入: &c/musterplayer cancel'
    musterplayer-end-tips: '结束召集输入: &c/musterplayer end'
    musterplayer-accept-tips: '同意召集输入: &c/musterplayer ccept'
    musterplayer-deny-tips: '拒绝召集输入: &c/musterplayer deny'
    musterplayer-others-tips: '所有玩家处理召集请求后或发起者提前结束召集，才会进行传送'
    musterplayer-apply-error: '没有需要处理的召集请求'
    musterplayer-player-leave-convenor: '召集者&3%player%&7已离开服务器，已取消此次召集'
    musterplayer-player-leave-callee: '被召集者&3%player%&7已离开服务器，已在被召集列表中移除该玩家'
    musterplayer-console-error: '控制台仅能使用&cmusterplayer cancel&7指令取消玩家召集'
    musterplayer-command-error: '召集指令错误，正确格式: &c/musterplayer <参数>'