#这是一个配置文件
plugin-message:
  message-prefix: '&e[Enhancements] &7'
  reload-message: '配置文件重载成功'
  command-args-error: '子指令错误或无子指令，正确格式：/enhancements <子指令>'
  command-no-permission: '你没有执行该主指令的权限'

join-and-leave-server-message:
  enable: true
  message:
    player-join-server-message: '&a%player% join server'
    player-leave-server-message: '&c%player% leave server'
join-server-welcome:
    enable: true
    message:
      join-server-welcome-message:
        - '&c欢迎加入本服务器1'
        - '&c欢迎加入本服务器2'
        - '&c欢迎加入本服务器3'
heal:
  enable: true
  message:
    heal-no-permission: '你没有执行恢复生命值指令的权限'
    heal-self: '你已恢复生命值'
    heal-others: '你已恢复&3%others-player%&7的生命值'
    heal-others-no-permission: '你没有执行恢复他人生命值指令的权限'
    heal-by-others: '你已被&3%player%&7恢复生命值'
    heal-by-console: '你已被服务器恢复生命值'
    heal-console-error: '控制台请执行恢复他人生命值的指令：heal <玩家名称>'
    heal-command-error: '恢复生命值指令格式错误，正确格式：/heal [玩家名称]'
feed:
  enable: false
  message:
    feed-no-permission: '你没有执行恢复饱食度指令的权限'
    feed-self: '你已恢复饱食度'
    feed-others: '你已恢复&3%others-player%&7的饱食度'
    feed-others-no-permission: '你没有执行恢复他人饱食度指令的权限'
    feed-by-others: '你已被&3%player%&7恢复饱食度'
    feed-by-console: '你已被服务器恢复饱食度'
    feed-console-error: '控制台请执行恢复他人饱食度的指令：feed <玩家名称>'
    feed-command-error: '恢复饱食度指令格式错误，正确格式：/feed [玩家名称]'
#当启用恢复生命值和饱食度指令时该功能自动自动，无需设置是否启用
healandfeed:
  message:
    heal-and-feed-no-permission: '你没有执行恢复生命值和饱食度指令的权限'
    heal-and-feed-self: '你已恢复生命值和饱食度'
    heal-and-feed-others: '你已恢复&3%others-player%&7的生命值和饱食度'
    heal-and-feed-others-no-permission: '你没有执行恢复他人生命值和饱食度指令的权限'
    heal-and-feed-by-others: '你已被&3%player%&7恢复生命值和饱食度'
    heal-and-feed-by-console: '你已被服务器恢复生命值和饱食度'
    heal-and-feed-console-error: '控制台请执行恢复他人生命值和饱食度的指令：healandfeed <玩家名称>'
    heal-and-feed-command-error: '恢复生命值和饱食度指令格式错误，正确格式：/healandfeed [玩家名称]'