name: UtilityToolbox
version: '${project.version}'
main: com.yishian.Main
api-version: 1.13

commands:
  UtilityToolbox:
    description: 插件主指令
  heal:
    description: 恢复生命值
  feed:
    description: 恢复饱食度
  healandfeed:
    description: 恢复生命值和饱食度
  fly:
    description: 开关飞行
  flyspeed:
    description: 修改飞行速度
  walkspeed:
    description: 修改移动速度
  tpa:
    description: 申请传送至该玩家位置
  tpacancel:
    description: 取消传送请求
  tpaccept:
    description: 同意传送请求
  tpadeny:
    description: 拒绝传送请求
  sethome:
    description: 设置家
  home:
    description: 回家
  showtextcode:
    description: 展示文本代码
  killself:
    description: 自杀
  back:
    description: 返回
  teleport:
    description: 切换服务器是否允许传送
  copyres:
    description: 复制主手上的物品
  playmode:
    description: 模式切换
  setsnaptp:
    description: 设置临时传送点
  snaptp:
    description: 回到临时传送点
  musterplayer:
    description: 召集玩家
  autorespawnback:
    description: 自动重生后回到死亡位置
  autorespawn:
    description: 自动重生
  sendconsole:
    description: 向控制台发送指令

#设置权限的一些特殊属性，无法在代码中设置的属性可以在这里设置
##设置权限默认值
##设置权限的子权限与子权限的描述
permissions:
  UtilityToolbox.heal:
    #设置子权限
    children:
      #设置子权限是否跟随父权限，true为跟随，false为相反
      UtilityToolbox.heal.others: false
    #设置权限的描述
    description: 恢复生命值的权限

  UtilityToolbox.feed:
    children:
      UtilityToolbox.feed.others: false
    description: 恢复饱食度的权限

  UtilityToolbox.fly:
    children:
      UtilityToolbox.fly.others: false
    description: 开关飞行的权限

  UtilityToolbox.flyspeed:
    children:
      UtilityToolbox.flyspeed.others: false
    description: 修改飞行速度的权限

  UtilityToolbox.walkspeed:
    children:
      UtilityToolbox.walkspeed.others: false
    description: 修改移动速度的权限

  UtilityToolbox.sethome:
    default: true
    description: 设置家的权限的权限

  UtilityToolbox.tpa:
    #默认是op，true为默认拥有该权限，false为默认没有该权限
    default: true
    description: 申请传送至该玩家位置的权限

  UtilityToolbox.playmode:
    children:
      UtilityToolbox.playmode.creative: false
      UtilityToolbox.playmode.survival: false
      UtilityToolbox.playmode.adventure: false
      UtilityToolbox.playmode.spectator: false
    description: 切换游戏模式的权限

  UtilityToolbox.back:
    default: true
    description: 返回的权限

  UtilityToolbox.copyres:
    description: 复制主手上的物品的权限

  UtilityToolbox.killself:
    default: true
    description: 自杀的权限

  UtilityToolbox.teleport:
    description: 切换服务器是否允许传送的权限

  UtilityToolbox.setsnaptp:
    default: true
    description: 设置临时传送点的权限

  UtilityToolbox.musterplayer:
    description: 召集玩家的权限

  UtilityToolbox.autorespawnback:
    default: true
    description: 自动重生后回到死亡位置的权限

  UtilityToolbox.autorespawn:
    default: true
    description: 自动重生的权限

  UtilityToolbox.sendconsole:
    description: 向控制台发送指令的权限

  UtilityToolbox.RedStoneDestroyMessage:
    description: 是否能看到红石被销毁的消息的权限

  UtilityToolbox.LimitFlowMessage:
    description: 是否能看到流体被限制的消息的权限

  UtilityToolbox.PlayerFrequencyAttacksKickMessage:
    description: 是否能看到玩家频繁攻击的消息的权限