name: Enhancements
version: '${project.version}'
main: com.yishian.Main
api-version: 1.18

commands:
  heal:
    description: 恢复生命值
  feed:
    description: 恢复饱食度
  healandfeed:
    description: 恢复生命值和饱食度