name: UtilityToolbox
version: '${project.version}'
main: com.yishian.Main
api-version: 1.13

commands:
  UtilityToolbox:
    description: 插件主指令
  heal:
    description: 恢复生命值
  feed:
    description: 恢复饱食度
  healandfeed:
    description: 恢复生命值和饱食度
  fly:
    description: 开关飞行
  flyspeed:
    description: 修改飞行速度
  walkspeed:
    description: 修改移动速度

permissions:
  UtilityToolbox.heal:
    default: op
    children:
      UtilityToolbox.heal.others: false
    description: 恢复生命值

  UtilityToolbox.feed:
    default: op
    children:
      UtilityToolbox.feed.others: false
    description: 恢复饱食度

  UtilityToolbox.fly:
    default: op
    children:
      UtilityToolbox.fly.others: false
    description: 开关飞行

  UtilityToolbox.flyspeed:
    default: op
    children:
      UtilityToolbox.flyspeed.others: false
    description: 修改飞行速度

  UtilityToolbox.walkspeed:
    default: op
    children:
      UtilityToolbox.walkspeed.others: false
    description: 修改移动速度