name: UtilityToolbox
version: '${project.version}'
main: com.yishian.Main
api-version: 1.13

commands:
  UtilityToolbox:
    description: 插件主指令
  heal:
    description: 恢复生命值
  feed:
    description: 恢复饱食度
  healandfeed:
    description: 恢复生命值和饱食度
  fly:
    description: 开关飞行
  flyspeed:
    description: 修改飞行速度
  walkspeed:
    description: 修改移动速度
  tpa:
    description: 申请传送至该玩家位置
  tpacancel:
    description: 取消传送请求
  tpaccept:
    description: 同意传送请求
  tpadeny:
    description: 拒绝传送请求
  sethome:
    description: 设置家
  home:
    description: 回家
  showtextcode:
    description: 展示文本代码
  killself:
    description: 自杀
  back:
    description: 返回
  teleport:
    description: 切换服务器是否允许传送
  copyres:
    description: 复制主手上的物品
  playmode:
    description: 模式切换
  setsnaptp:
    description: 设置临时传送点
  snaptp:
    description: 回到临时传送点
  musterplayer:
    description: 召集玩家
  autorespawnback:
    description: 自动重生后回到死亡位置
  autorespawn:
    description: 自动重生
  sendconsole:
    description: 向控制台发送指令

permissions:
  UtilityToolbox.heal:
    default: op
    children:
      UtilityToolbox.heal.others: false
    description: 恢复生命值

  UtilityToolbox.feed:
    default: op
    children:
      UtilityToolbox.feed.others: false
    description: 恢复饱食度

  UtilityToolbox.fly:
    default: op
    children:
      UtilityToolbox.fly.others: false
    description: 开关飞行

  UtilityToolbox.flyspeed:
    default: op
    children:
      UtilityToolbox.flyspeed.others: false
    description: 修改飞行速度

  UtilityToolbox.walkspeed:
    default: op
    children:
      UtilityToolbox.walkspeed.others: false
    description: 修改移动速度

  UtilityToolbox.tpa:
    default: op
    description: 申请传送至该玩家位置

  UtilityToolbox.AntiRedStoneMessage:
    default: op
    description: 是否能看到高频红石被销毁的消息

  UtilityToolbox.LimitFlowMessage:
    default: op
    description: 是否能看到流体被限制的消息

  UtilityToolbox.playmode:
    default: op
    children:
      UtilityToolbox.playmode.creative: false
      UtilityToolbox.playmode.survival: false
      UtilityToolbox.playmode.adventure: false
      UtilityToolbox.playmode.spectator: false
    description: 切换游戏模式